NewsFeed/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainsite/', include("mainsite.urls"))
]

mainsite/urls.py
from django.urls import path
from mainsite.views import index, news_for_category

app_name = "mainsite"

urlpatterns = [
    path('index', index, name='index'),
    path('category/<int:category_id>',news_for_category, name='category_news'),
]

mainsite/models.py
from django.db import models

# Create your models here.

class ArticleCategory(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

class Article(models.Model):
	category = models.ForeignKey(ArticleCategory, on_delete = models.CASCADE)
	title = models.CharField(max_length = 200)
	description = models.CharField(max_length=400)
	content = models.TextField()


	def __str__(self):
		return self.title
		

mainsite/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from mainsite.models import Article, ArticleCategory
# Create your views here.

def index(request):
	articles = Article.objects.all().order_by('-id')[0:10]
	categories = ArticleCategory.objects.all()
	page = loader.get_template("mainsite/index.html")
	context = {
	"articles": articles,
	"categories": categories,
	"page_title": "Home page"
	}
	return HttpResponse(page.render(context, request))

def news_for_category(request, category_id):
	category = ArticleCategory.objects.get(id=category_id)
	articles = Article.objects.filter(category=category)
	categories = ArticleCategory.objects.all()
	page = loader.get_template("mainsite/index.html")
	context = {
	"articles": articles,
	"categories": categories,
	"page_title": category.name
	}
	return HttpResponse(page.render(context, request))

templates/mainsite/index.html
<!DOCTYPE html>
<html>
<head>
	<title>{{page_title}}</title>

<style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
  border-radius: 4px;
}

li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover {
  background-color: #111;
}
.article {
	background-color: #EDEDED;
	padding: 5px;
	border-radius: 4px;
	margin: 5px;
}
</style>
</head>
<body>
<ul>
	<li><a href="{% url 'mainsite:index' %}">home</a></li>
	{% for element in categories %}
	<li><a href="{% url 'mainsite:category_news' element.id %}">{{element.name}}</a></li>
	{% endfor %}
</ul>



{% for element in articles %}
<div class="article">

	<h3>{{element.title}} </h3>
	<p>{{element.content}} </p>
</div>
{% endfor %}
</body>
</html>